In [1]:
import numpy
n=numpy.arange(27)
n

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

In [2]:
n.reshape(3,3,3)

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [3]:
m=numpy.asarray([[1,2,3,4,5,6],[7,8,9,10,11,12], [13,14,15,16,17,18]])
print(m)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]]


# reading image

In [4]:
import cv2
img_g = cv2.imread(r"data\smallgray.png", 0)
img_g

array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182]], dtype=uint8)

In [5]:
img_c = cv2.imread(r"data\smallgray.png", 1)
img_c

array([[[187, 187, 187],
        [158, 158, 158],
        [104, 104, 104],
        [121, 121, 121],
        [143, 143, 143]],

       [[198, 198, 198],
        [125, 125, 125],
        [255, 255, 255],
        [255, 255, 255],
        [147, 147, 147]],

       [[209, 209, 209],
        [134, 134, 134],
        [255, 255, 255],
        [ 97,  97,  97],
        [182, 182, 182]]], dtype=uint8)

In [6]:
cv2.imwrite(r"data\newsmallgray.png", img_c)


True

In [12]:
new_img_c = numpy.random.randint(0, 255+1, size=(120,120,3))
cv2.imwrite(r"data\new_img.png", new_img_c)

True

In [48]:
print(new_img_c[0, 2:4, 0:2])
print(new_img_c[0, 0, 0])
print(new_img_c[0, 0, 1])
for i in new_img_c.flat[:10]:
    print(i)

[[210  93]
 [ 92  88]]
150
5
150
5
244
223
25
190
210
93
39
92


In [51]:
my_ar_h = numpy.hstack((new_img_c[0, 9:12, 1], new_img_c[0, 4:7, 0]))
print(my_ar_h)
my_ar_v = numpy.vstack((new_img_c[1, 9:12, 1], new_img_c[-1, 4:7, 0]))
print(my_ar_v)

[ 79 181 137 218 139 111]
[[ 97  67 144]
 [249 193 141]]


In [58]:
my_ar_h_split = numpy.hsplit(my_ar_h, 3)
print(my_ar_h_split)
my_ar_v_split = numpy.vsplit(my_ar_v, 2)
print(my_ar_v_split)
my_ar_v_split_h = numpy.hsplit(my_ar_v, 3)
print(my_ar_v_split_h)

[array([ 79, 181]), array([137, 218]), array([139, 111])]
[array([[ 97,  67, 144]]), array([[249, 193, 141]])]
[array([[ 97],
       [249]]), array([[ 67],
       [193]]), array([[144],
       [141]])]
